### ISSUE TITLE
How to read from DAI Medianizer

### ISSUE THREAD

**Issue by kendricktan** [studydefi/studydefi.com#24]
Due: `0000 24th April UTC +0`

**Comment by adrianmcli** [comment]
I can see this being at least 3 different blog posts:

1. How to read price of a token from Uniswap
2. How to read price of a token from MakerDAO Medianizer
3. How to read price of a token from Kyber

**Comment by kendricktan** [comment]
Does it need to be so specific?

**Comment by adrianmcli** [comment]
I think it's a better idea for SEO.

**Comment by adrianmcli** [comment]
If you don't want to, you can do a general one now, and I can do a more in-depth one later on.

**Comment by kendricktan** [comment]
SEO makes sense, lets hold off from DEX's from now and just do Maker's medianizer
